---
- hosts: update
  gather_facts: no
  vars_files:
  - vault/passwords
  - vault/msg_groups.yml
  vars:
    mail_body_file: "/tmp/ansible_mailing_tmtghujm" 
    start_file: "/tmp/ansible_start_tmtghujm"
    connected_file: "/tmp/ansible_connected_tmtghujm"
    needsrestart_file: "/tmp/ansible_needsrestart_tmtghujm"
    updated_file: "/tmp/ansible_updated_tmtghujm"
    restared_file: "/tmp/ansible_restared_tmtghujm"
    tmp1_file: "/tmp/ansible_tmp1_tmtghujm"
    tmp2_file: "/tmp/ansible_tmp2_tmtghujm"
    tmp3_file: "/tmp/ansible_tmp3_tmtghujm"
    tmp4_file: "/tmp/ansible_tmp4_tmtghujm"
    tmp5_file: "/tmp/ansible_tmp5_tmtghujm"
    tmp6_file: "/tmp/ansible_tmp6_tmtghujm"
    no_restart:
      - node01.nfs.info
  order: sorted

  pre_tasks:
    - name: run included Pre-tasks
      include: "{{outer_item}}"
      loop_control:
        loop_var: outer_item
      loop:
      - tasks/get_date_start

  tasks:
    - name: run included tasks
      include: tasks/get_date_start

  post_tasks:
    - name: run included post tasks
      include: tasks/get_date_start
