---
- hosts: update
  gather_facts: no
  vars_files:
  - vault/passwords
  - vault/msg_groups.yml
  vars:
    mail_body_file: "/tmp/ansible_mailing_tmtghujm" 
    start_file: "/tmp/ansible_start_tmtghujm"
    connected_file: "/tmp/ansible_connected_tmtghujm"
    needsrestart_file: "/tmp/ansible_needsrestart_tmtghujm"
    updated_file: "/tmp/ansible_updated_tmtghujm"
    restared_file: "/tmp/ansible_restared_tmtghujm"
    tmp1_file: "/tmp/ansible_tmp1_tmtghujm"
    tmp2_file: "/tmp/ansible_tmp2_tmtghujm"
    tmp3_file: "/tmp/ansible_tmp3_tmtghujm"
    tmp4_file: "/tmp/ansible_tmp4_tmtghujm"
    tmp5_file: "/tmp/ansible_tmp5_tmtghujm"
    tmp6_file: "/tmp/ansible_tmp6_tmtghujm"
    no_restart:
      - node01.nfs.info
  order: sorted

  pre_tasks:
    - name: run included Pre-tasks
      include_tasks: "{{outer_item}}"
      loop_control:
        loop_var: outer_item
      loop:
      - tasks/get_date_start
      - tasks/create_file_start
      - tasks/create_files_clear
      - tasks/create_files_touch

  tasks:
    - name: run included tasks
      include_tasks: "{{outer_item}}"
      loop_control:
        loop_var: outer_item
      loop:
      - tasks/update_reboot
      - tasks/create_summery

  post_tasks:
    - name: run included tasks
      include_tasks: "{{outer_item}}"
      loop_control:
        loop_var: outer_item
      loop:
      - tasks/get_date_end
      - tasks/email
      - tasks/create_files_clear
