---
- hosts: update
  gather_facts: no
  vars_files:
  - vault/passwords
  - vault/msg_groups.yml
  vars:
    mail_body_file: "/tmp/ansible-mailing-tmtghujm" 
  order: sorted

  tasks:
    - name: run included tasks
      include: update_reboot_task.yml

  post_tasks:
    - name: run included post tasks
      include: email_task.yml
