---
- hosts: update
  gather_facts: no
  vars_files:
  - vault/passwords
  - vault/msg_groups.yml
  vars:
    mail_body_file: "/tmp/ansible-mailing-tmtghujm" 
  order: sorted
  tasks:

    - name: run included tasks
      include: update_reboot_task.yml
      include: email_task.yml
