---
- hosts: setupAnsible 
  gather_facts: no
  remote_user: alex
  vars:
    user: ansible

  tasks:
    - name: Setup sshd permission for users in /etc/ssh/sshd_config
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match User {{ user }}
              ClientAliveInterval 0
              PasswordAuthentication no
              X11Forwarding no
              AllowTcpForwarding no
              PermitTTY no
      notify:
        - Restart_sshd

    - name: Creating user "{{ user }}"
      user: 
        name: "{{ user }}"

    - name: Edit sudoers.d
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: |
          ansible  ALL=(ALL)       NOPASSWD: ALL

    - name: Create .ssh dir
      ansible.builtin.file:
        path: /home/{{ user }}/.ssh
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0700

    - name: touch authorized_keys
      shell: touch /home/{{ user }}/.ssh/authorized_keys

    - name: set perms authorized_keys
      ansible.builtin.file:
        path: /home/{{ user }}/.ssh/authorized_keys
        state: file
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600

    - name: Add key authorized_keys
      ansible.builtin.lineinfile:
        path: /home/{{ user }}/.ssh/authorized_keys
        line: from="192.168.0.71" ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN9NoEX5pC3HkOpTRyZwk7oWgP2mxnT9Dzn9rTM5hE0B/Uiz+m/zKU8sTR0I5/s5SPFd/Xk/z70p9HsA0L1Mkoo= ansible@node02.savvyaxl.com.br
        state: present

  handlers:
    - name: Restart_sshd
      service:
        name: sshd
        state: restarted


