---
- hosts: update 
  gather_facts: yes
  tasks:
    - name: Setup sudoers
      copy:
        src: files/sudoers
        dest: /etc/sudoers
        mode: 0440
        owner: root
        group: root

    - name: Setup sshd permission for ansible in /etc/ssh/sshd_config
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          Match User ansible
              PasswordAuthentication no
              X11Forwarding no
              AllowTcpForwarding no
              PermitTTY no
      notify:
        - Restart_sshd
      when: ansible_facts['distribution_release'] != "Plow" and ansible_facts['distribution'] != "Fedora"

    - name: Setup /etc/ssh/sshd_config.d/ansible.conf
      copy:
        src: files/sshd_config_ansible
        dest: /etc/ssh/sshd_config.d/ansible.conf
        mode: 0400
        owner: root
        group: root
      notify:
        - Restart_sshd
      when: ansible_facts['distribution_release'] == "Plow" or ansible_facts['distribution'] == "Fedora"

    - name: Modify authorized_keys 1
      ansible.builtin.lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: from="192.168.0.56" ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2bue64RNaff+S7rFIWObd41R2Moa5UMPQjJ3EuwMq2Ys68ZiYVd2/a6Y5DS+WL+FrhuqeWCyCKym+vgmxRE1u6Z49IjMhSKPWr/IkuEhlLFW3K35d4PC84XsAo+NpHkoTQCH/wlvR7806umsQYugvL0MFSvy/w9g316N59dmJ+S93z0/Y+ANzFou1GYNsiB42NE9zq1JX20B3mVhsr3jqbOpbS7GiuzvZJ6F7zIdDyFmG+3SjzdYPK5iLJEQriifhS42wvgcBz7agHL1lR0thhimu/OSNCyOqy1sdteKP+HJ4XTRNmp10oLp76sZUFBVxsMw94Laxb1+EZ1f9yYglcdqKVdExgtP7quVQB/7xc7oWsMgybIl1Sa6sspwWT71ig2jEJY8tO8FoSVAPm0YObfYTOA2YBlTgvFIu+pgjhtL7cUbx15epdsIyj8odRPmQmOeOzQRecf+I6MBPtZ0GNG/2mKUE2O/1pS1fju6eTsLmKjgyANwS+DY/sSNorX8= ansible@ansible.local
        state: present
        owner: ansible
        group: ansible
      notify:
        - Restart_sshd

    - name: Modify authorized_keys 2
      ansible.builtin.lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2bue64RNaff+S7rFIWObd41R2Moa5UMPQjJ3EuwMq2Ys68ZiYVd2/a6Y5DS+WL+FrhuqeWCyCKym+vgmxRE1u6Z49IjMhSKPWr/IkuEhlLFW3K35d4PC84XsAo+NpHkoTQCH/wlvR7806umsQYugvL0MFSvy/w9g316N59dmJ+S93z0/Y+ANzFou1GYNsiB42NE9zq1JX20B3mVhsr3jqbOpbS7GiuzvZJ6F7zIdDyFmG+3SjzdYPK5iLJEQriifhS42wvgcBz7agHL1lR0thhimu/OSNCyOqy1sdteKP+HJ4XTRNmp10oLp76sZUFBVxsMw94Laxb1+EZ1f9yYglcdqKVdExgtP7quVQB/7xc7oWsMgybIl1Sa6sspwWT71ig2jEJY8tO8FoSVAPm0YObfYTOA2YBlTgvFIu+pgjhtL7cUbx15epdsIyj8odRPmQmOeOzQRecf+I6MBPtZ0GNG/2mKUE2O/1pS1fju6eTsLmKjgyANwS+DY/sSNorX8= ansible@ansible.local
        state: absent
        owner: ansible
        group: ansible
      notify:
        - Restart_sshd

  handlers:
    - name: Restart_sshd
      service:
        name: sshd
        state: restarted


