---
- hosts: update
  tasks:
    - name: Update all installed packages using YUM module
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
        #autoremove: yes
      register: yum_updates

    - name: Install Yum Utilities
      yum:
        name: yum-utils
        state: latest

    - name: check to see if we need a reboot
      command: needs-restarting -r
      register: result
      ignore_errors: yes
      changed_when: false

    - debug:
        var: yum_updates

    - debug:
        var: result.stdout_lines

