---
- hosts: setup
  gather_facts: no
  tasks:
    - name: Update all installed packages using YUM module
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_updates

    - name: Install Yum Utilities
      yum:
        name: yum-utils
        state: latest

    - name: check to see if we need a reboot
      command: needs-restarting -r
      register: result
      ignore_errors: yes

    - debug:
        var: yum_updates

    - debug:
        var: result.stdout_lines

    - name: Reboot Server if Necessary
      reboot:
      async: 1
      poll: 0
      when: result.rc == 1 and inventory_hostname != "ansible"
      ignore_errors: yes

    - name: Pausing to allow server to shutdown and terminate our SSH connection
      pause: seconds=100
      when: result.rc == 1
#
    - name: Verify reboot
      command: uptime
      when: result.rc == 1

