---
- hosts: update
  gather_facts: no
  vars_files:
  - vault/passwords
  - vault/msg_groups.yml
  vars:
    mail_body_file: "/tmp/ansible_mailing_tmtghujm" 
    start_file: "/tmp/ansible_start_tmtghujm"
    end_file: "/tmp/ansible_end_tmtghujm"
    compare_file: "/tmp/ansible_compare_tmtghujm"
  order: sorted

  tasks:
    - name: Clear the files
      file:
        state: absent
        path: "{{item}}"
      delegate_to: localhost
      become: false
      run_once: true
      loop:
        - "{{start_file}}"
        - "{{end_file}}"
        - "{{compare_file}}"

    - name: Get timestamp from the system
      shell: "date"
      delegate_to: localhost
      run_once: true
      register: start_date
      become: false

    - name: Create the start file
      shell: "echo {{ inventory_hostname }} >> {{ start_file }}"
      delegate_to: localhost
      become: false

    - name: Update all installed packages using YUM module
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_updates

    - name: check to see if we need a reboot
      command: needs-restarting -r
      register: needsrestart
      ignore_errors: yes

    - name: Reboot Server if Necessary
      shell: sleep 5 && reboot
      async: 1
      poll: 0
      timeout: 10
      when: needsrestart.rc == 1 and inventory_hostname != "ansible"
      ignore_errors: yes
      register: rebooted

    - name: debug
      debug:
        var: rebooted

    - name: debug
      debug:
        var: needsrestart

    - name: Pausing to allow server to shutdown and terminate our SSH connection
      pause: seconds=200
      when: needsrestart.rc == 1 and inventory_hostname != "ansible"
#
    - name: Verify reboot
      command: uptime
      register: uptime


    - name: Get timestamp from the system
      shell: "date"
      delegate_to: localhost
      run_once: true
      register: end_date
      become: false

    - name: Check if there is {{mail_body_file}}
      file:
        state: absent
        path: "{{mail_body_file}}"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Create {{mail_body_file}}
      file:
        state: touch
        path: "{{mail_body_file}}"
      delegate_to: localhost
      run_once: true
      become: false

    - name: Use j2 template to create body part
      template:
        src: templates/body.j2
        dest: /tmp/{{inventory_hostname}}.body.html
      delegate_to: localhost
      become: false

    - name: Create the end file
      shell: "echo {{ inventory_hostname }} >> {{ end_file }}"
      delegate_to: localhost
      become: false

    - name: Create the summery file
      shell: |
        (for x in $(cat {{start_file}} | sort)
        do
        z=" Failed"
        for y in $(cat {{end_file}})
        do
        if [[ "x$x" == "x$y" ]]
        then
        z=" Success"
        fi
        done
        echo "$x $z <BR>"
        done ) >> {{mail_body_file}}
      delegate_to: localhost
      become: false
      run_once: True

    - name: Start time
      shell: |
        echo "<p>Start: {{ start_date.stdout }}</p>" >> {{ mail_body_file }}
      delegate_to: localhost
      become: false
      run_once: True

    - name: End time
      shell: |
        echo "<p>End: {{ end_date.stdout }}</p>" >> {{ mail_body_file }}
      delegate_to: localhost
      become: false
      run_once: True

    - name: add the individual runs
      shell: "cat /tmp/{{inventory_hostname}}.body.html  >> {{mail_body_file}}"
      delegate_to: localhost
      become: false

    - name: get the mail body to variable
      register: mail_body
      command: "cat {{mail_body_file}}"
      delegate_to: localhost
      run_once: True

    - name: Sending an e-mail using gmail with app key
      community.general.mail:
        host: "{{ gmail.host }}"
        port: "{{ gmail.port }}"
        username: "{{ gmail.username  | default(omit) }}"
        password: "{{ gmail.password  | default(omit) }}"
        subtype: html
        to: "{{ updateAll.to }}"
        from: "{{ updateAll.from }}"
        subject: Ansible-report for {{start_date.stdout}}
        body: "{{mail_body.stdout}}"
        secure: "{{ gmail.secure }}"
      delegate_to: localhost
      run_once: True
      register: emailresult
      until: emailresult is not failed
      retries: 3
      delay: 20
